"""Preflop drill scenarios for the Drill Lab module."""

import random
from typing import Any

SCENARIOS: list[dict[str, Any]] = [
    # --- Open raises from each position ---
    {
        "id": "pf-01",
        "position": "UTG",
        "stack_depth": 100,
        "action_so_far": "You are UTG. Everyone folds to you. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Raise to 25"},
        ],
        "correct_action": "raise",
        "feedback_good": "Standard open from UTG. You have the best range advantage and should build the pot.",
        "feedback_ok": "A call isn't terrible but you miss the chance to isolate and build the pot.",
        "feedback_poor": "Fold is way too tight here. UTG opens roughly the top 22% of hands.",
    },
    {
        "id": "pf-02",
        "position": "MP",
        "stack_depth": 100,
        "action_so_far": "You are MP. Everyone folds to you. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Raise to 25"},
        ],
        "correct_action": "raise",
        "feedback_good": "MP open is standard. You still have strong range advantage.",
        "feedback_ok": "Limp/call is passive. You want to build the pot with your strong range.",
        "feedback_poor": "Folding here is far too tight from MP.",
    },
    {
        "id": "pf-03",
        "position": "CO",
        "stack_depth": 100,
        "action_so_far": "You are on the Cutoff. Everyone folds to you. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Raise to 25"},
        ],
        "correct_action": "raise",
        "feedback_good": "The CO is a powerful position. Open your entire profitable range here.",
        "feedback_ok": "Calling is too passive — you give the blinds a chance to see a flop cheaply.",
        "feedback_poor": "Fold is far too tight from the Cutoff.",
    },
    {
        "id": "pf-04",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "You are on the Button. Everyone folds to you. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Raise to 25"},
        ],
        "correct_action": "raise",
        "feedback_good": "BTN is the best position postflop. Open aggressively here — you can profitably raise a very wide range.",
        "feedback_ok": "Calling is too passive. You want to build the pot and apply pressure.",
        "feedback_poor": "Folding from the Button is almost never correct when it's folded to you.",
    },
    {
        "id": "pf-05",
        "position": "SB",
        "stack_depth": 100,
        "action_so_far": "You are in the Small Blind. Everyone folds to you. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 5"},
            {"action": "raise", "label": "Raise to 30"},
        ],
        "correct_action": "raise",
        "feedback_good": "From the SB you should almost always raise or fold. A min-raise to 30 is standard.",
        "feedback_ok": "Calling is acceptable with speculative hands but generally you want to raise or fold.",
        "feedback_poor": "Folding is too tight from the SB when it's folded around.",
    },
    # --- 3-bet decisions ---
    {
        "id": "pf-06",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You are in the BB. BTN opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "raise",
        "feedback_good": "3-betting from the BB vs BTN open is standard. You deny the BTN their positional advantage.",
        "feedback_ok": "Calling is fine with medium-strength hands but 3-bet or fold is higher EV.",
        "feedback_poor": "Folding is too tight — you need to defend at least 35-40% of hands vs a BTN open.",
    },
    {
        "id": "pf-07",
        "position": "SB",
        "stack_depth": 100,
        "action_so_far": "You are in the SB. CO opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "raise",
        "feedback_good": "3-betting from SB vs CO is strong. You take initiative and put pressure on the opener.",
        "feedback_ok": "Calling is acceptable but 3-bet or fold is the higher-EV line.",
        "feedback_poor": "Folding is too tight from the SB vs a CO open.",
    },
    {
        "id": "pf-08",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You are in the BB. UTG opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "call",
        "feedback_good": "UTG has a strong range. Calling with a wide but capped range is correct here.",
        "feedback_ok": "3-bet is acceptable with premium hands but UTG's range is strong.",
        "feedback_poor": "Folding is too tight — you need to defend roughly 20-25% vs UTG.",
    },
    {
        "id": "pf-09",
        "position": "CO",
        "stack_depth": 100,
        "action_so_far": "You are on the CO. UTG opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct. UTG has a very strong range and you're out of position. Folding is the highest-EV play.",
        "feedback_ok": "Calling is too loose — UTG's range dominates your CO calling range.",
        "feedback_poor": "3-betting here is reckless. UTG's range is too strong to bluff into.",
    },
    {
        "id": "pf-10",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "You are on the Button. MP opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "raise",
        "feedback_good": "3-betting from the BTN vs MP is excellent. You have position and can apply maximum pressure.",
        "feedback_ok": "Calling is fine but 3-bet is higher EV with your positional advantage.",
        "feedback_poor": "Folding is far too tight from the BTN.",
    },
    # --- BB defense scenarios ---
    {
        "id": "pf-11",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You are in the BB. SB opens to 15 (min-raise). Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 15"},
            {"action": "raise", "label": "3-bet to 50"},
        ],
        "correct_action": "call",
        "feedback_good": "Great call. You're getting great odds to see a flop from the BB vs a min-raise.",
        "feedback_ok": "3-bet is fine with premiums but calling is higher EV with a wide range.",
        "feedback_poor": "Folding is way too tight — you need to defend at least 50%+ vs a min-raise.",
    },
    {
        "id": "pf-12",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You are in the BB. BTN opens to 30. SB folds. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 30"},
            {"action": "raise", "label": "3-bet to 100"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You're getting 3:1 odds and have the advantage of acting last postflop.",
        "feedback_ok": "3-bet is fine with strong hands but calling is the default.",
        "feedback_poor": "Folding is too tight — you need to defend roughly 35-40% vs BTN.",
    },
    {
        "id": "pf-13",
        "position": "BB",
        "stack_depth": 40,
        "action_so_far": "You are in the BB (40bb effective). BTN opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "Jam for 400 (all-in)"},
        ],
        "correct_action": "raise",
        "feedback_good": "At 40bb, a 3-bet jam is the correct play with your strong-but-not-premium range.",
        "feedback_ok": "Calling is acceptable but you're risking too much of your stack to just call.",
        "feedback_poor": "Folding is too tight — you need to defend aggressively at 40bb.",
    },
    # --- SB play ---
    {
        "id": "pf-14",
        "position": "SB",
        "stack_depth": 100,
        "action_so_far": "You are in the SB. Folds to you. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Raise to 30"},
        ],
        "correct_action": "raise",
        "feedback_good": "Standard SB open. You raise to 30 with your entire profitable range.",
        "feedback_ok": "Calling is acceptable but raising is higher EV — you build the pot.",
        "feedback_poor": "Folding is too tight from the SB when it's folded to you.",
    },
    {
        "id": "pf-15",
        "position": "SB",
        "stack_depth": 100,
        "action_so_far": "You are in the SB. BTN opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "raise",
        "feedback_good": "3-betting from SB vs BTN is the standard play. You deny the BTN their positional edge.",
        "feedback_ok": "Calling is acceptable but 3-bet or fold is higher EV.",
        "feedback_poor": "Folding is too tight — you need to defend roughly 15-20% vs BTN from the SB.",
    },
    # --- Short stack play ---
    {
        "id": "pf-16",
        "position": "BTN",
        "stack_depth": 20,
        "action_so_far": "You are on the Button (20bb effective). Everyone folds to you. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Jam for 200 (all-in)"},
        ],
        "correct_action": "raise",
        "feedback_good": "At 20bb, you should jam or fold from the BTN. Jamming is higher EV.",
        "feedback_ok": "Calling is a mistake — you're risking too much of a short stack to just call.",
        "feedback_poor": "Folding is far too tight from the BTN at 20bb.",
    },
    {
        "id": "pf-17",
        "position": "CO",
        "stack_depth": 20,
        "action_so_far": "You are on the Cutoff (20bb effective). Everyone folds to you. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Jam for 200 (all-in)"},
        ],
        "correct_action": "raise",
        "feedback_good": "At 20bb, jam-or-fold is the correct strategy from the CO.",
        "feedback_ok": "Calling is a mistake with a short stack.",
        "feedback_poor": "Folding is too tight from the CO at 20bb.",
    },
    {
        "id": "pf-18",
        "position": "BB",
        "stack_depth": 20,
        "action_so_far": "You are in the BB (20bb effective). BTN opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "Jam for 200 (all-in)"},
        ],
        "correct_action": "raise",
        "feedback_good": "At 20bb, a 3-bet jam is the correct play with your strong-but-not-premium range.",
        "feedback_ok": "Calling is acceptable but you're risking too much of your stack.",
        "feedback_poor": "Folding is too tight — you need to defend aggressively at 20bb.",
    },
    # --- Limped pot scenarios ---
    {
        "id": "pf-19",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You are in the BB. Two players limped. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "check", "label": "Check"},
            {"action": "raise", "label": "Raise to 40"},
        ],
        "correct_action": "raise",
        "feedback_good": "Raising in a limped pot is excellent. You build the pot with your strong range.",
        "feedback_ok": "Checking is acceptable but raising is higher EV.",
        "feedback_poor": "Folding is never correct from the BB when you can check for free.",
    },
    {
        "id": "pf-20",
        "position": "SB",
        "stack_depth": 100,
        "action_so_far": "You are in the SB. Two players limped. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "check", "label": "Check"},
            {"action": "raise", "label": "Raise to 40"},
        ],
        "correct_action": "raise",
        "feedback_good": "Raising in a limped pot from the SB is strong. You build the pot and take initiative.",
        "feedback_ok": "Checking is acceptable but raising is higher EV.",
        "feedback_poor": "Folding is never correct from the SB when you can check for free.",
    },
    # --- Additional 3-bet spots ---
    {
        "id": "pf-21",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "You are on the Button. SB 3-bets to 90. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 90"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You have position and can realize your equity well.",
        "feedback_ok": "4-bet is fine with premiums but calling is the default.",
        "feedback_poor": "Folding is too tight — you need to defend roughly 10-12% vs a SB 3-bet.",
    },
    {
        "id": "pf-22",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You are in the BB. SB 3-bets to 90. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 90"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You're out of position but getting great odds.",
        "feedback_ok": "4-bet is fine with premiums but calling is the default.",
        "feedback_poor": "Folding is too tight — you need to defend roughly 10-12% vs a SB 3-bet.",
    },
    {
        "id": "pf-23",
        "position": "CO",
        "stack_depth": 100,
        "action_so_far": "You are on the CO. BTN 3-bets to 90. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 90"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. BTN's 3-bet range is strong and you're out of position.",
        "feedback_ok": "Calling is too loose — BTN's range dominates your CO calling range.",
        "feedback_poor": "4-betting here is reckless. BTN's range is too strong.",
    },
    {
        "id": "pf-24",
        "position": "UTG",
        "stack_depth": 100,
        "action_so_far": "You are UTG. MP 3-bets to 90. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 90"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. MP's 3-bet range is strong and you're out of position.",
        "feedback_ok": "Calling is too loose — MP's range dominates your UTG calling range.",
        "feedback_poor": "4-betting here is reckless. MP's range is too strong.",
    },
    {
        "id": "pf-25",
        "position": "BTN",
        "stack_depth": 40,
        "action_so_far": "You are on the Button (40bb effective). CO opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "raise",
        "feedback_good": "3-betting from the BTN at 40bb is standard. You deny the CO their positional edge.",
        "feedback_ok": "Calling is acceptable but 3-bet is higher EV.",
        "feedback_poor": "Folding is too tight — you need to defend aggressively at 40bb.",
    },
    # --- 4-bet decisions (pf-26 to pf-32) ---
    {
        "id": "pf-26",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "You open from the BTN to 25. BB 3-bets to 90. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 90"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "raise",
        "feedback_good": "4-betting is correct. You have position and a strong range from the BTN.",
        "feedback_ok": "Calling is acceptable but 4-bet is higher EV with your positional edge.",
        "feedback_poor": "Folding is too tight — you opened the BTN with a wide range.",
    },
    {
        "id": "pf-27",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You 3-bet from the BB to 90. BTN 4-bets to 220. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 220"},
            {"action": "raise", "label": "Jam for 1000 (all-in)"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. BTN's 4-bet range is very strong and you're out of position.",
        "feedback_ok": "Calling is too loose — BTN's range dominates your 3-bet calling range.",
        "feedback_poor": "Jamming is reckless with anything less than QQ+.",
    },
    {
        "id": "pf-28",
        "position": "SB",
        "stack_depth": 100,
        "action_so_far": "You 3-bet from SB to 90. BTN 4-bets to 220. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 220"},
            {"action": "raise", "label": "Jam for 1000 (all-in)"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. BTN's 4-bet is very strong and you're out of position from the SB.",
        "feedback_ok": "Calling is too loose — you need a very strong hand to continue.",
        "feedback_poor": "Jamming here is reckless without AA/KK.",
    },
    {
        "id": "pf-29",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "You open from the BTN to 25. SB 3-bets to 90. You 4-bet to 220. SB 5-bets to 500. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 500"},
            {"action": "raise", "label": "Jam for 1000 (all-in)"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. A 5-bet almost always means AA or KK. Save your chips.",
        "feedback_ok": "Jamming is only correct with AA/KK. Fold everything else.",
        "feedback_poor": "Calling is a huge mistake — you're crushed by the 5-bet range.",
    },
    {
        "id": "pf-30",
        "position": "CO",
        "stack_depth": 100,
        "action_so_far": "You open from the CO to 25. BTN 3-bets to 90. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 90"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. BTN's 3-bet range is strong and you're out of position.",
        "feedback_ok": "Calling is too loose — BTN's range dominates your CO calling range.",
        "feedback_poor": "4-betting here is reckless. BTN's range is too strong.",
    },
    {
        "id": "pf-31",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "You open from the BTN to 25. BB 3-bets to 90. You 4-bet to 220. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 220"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "raise",
        "feedback_good": "4-betting from the BTN vs BB is standard. You have position and range advantage.",
        "feedback_ok": "Calling is acceptable but 4-bet is higher EV.",
        "feedback_poor": "Folding is too tight — you opened the BTN with a wide range.",
    },
    {
        "id": "pf-32",
        "position": "UTG",
        "stack_depth": 100,
        "action_so_far": "You open from UTG to 25. CO 3-bets to 90. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 90"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. CO's 3-bet range is strong and you're out of position.",
        "feedback_ok": "Calling is too loose — CO's range dominates your UTG calling range.",
        "feedback_poor": "4-betting here is reckless. CO's range is too strong.",
    },
    # --- Squeeze plays (pf-33 to pf-36) ---
    {
        "id": "pf-33",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "UTG opens to 25. CO calls. You are in the BB. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "Squeeze to 100"},
        ],
        "correct_action": "raise",
        "feedback_good": "Squeezing is excellent. Two players have shown weakness — you can take the pot down.",
        "feedback_ok": "Calling is acceptable but squeezing is higher EV.",
        "feedback_poor": "Folding is too tight — you should defend aggressively with two callers.",
    },
    {
        "id": "pf-34",
        "position": "SB",
        "stack_depth": 100,
        "action_so_far": "MP opens to 25. BTN calls. You are in the SB. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "Squeeze to 100"},
        ],
        "correct_action": "raise",
        "feedback_good": "Squeezing from the SB vs MP+BTN is strong. You put pressure on both players.",
        "feedback_ok": "Calling is acceptable but squeezing is higher EV.",
        "feedback_poor": "Folding is too tight — you should defend aggressively.",
    },
    {
        "id": "pf-35",
        "position": "CO",
        "stack_depth": 100,
        "action_so_far": "UTG opens to 25. MP calls. You are on the CO. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "Squeeze to 100"},
        ],
        "correct_action": "raise",
        "feedback_good": "Squeezing is excellent. Two players have shown weakness — you can take the pot down.",
        "feedback_ok": "Calling is acceptable but squeezing is higher EV.",
        "feedback_poor": "Folding is too tight — you should squeeze with a wide range.",
    },
    {
        "id": "pf-36",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "UTG opens to 25. Two players call. You are on the Button. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "Squeeze to 100"},
        ],
        "correct_action": "raise",
        "feedback_good": "Squeezing from the BTN with multiple callers is excellent. You have position and initiative.",
        "feedback_ok": "Calling is acceptable but squeezing is higher EV.",
        "feedback_poor": "Folding is too tight — you should squeeze aggressively with multiple callers.",
    },
    # --- Facing 4-bets (pf-37 to pf-40) ---
    {
        "id": "pf-37",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You 3-bet from the BB to 90. BTN 4-bets to 220. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 220"},
            {"action": "raise", "label": "Jam for 1000 (all-in)"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. BTN's 4-bet range is very strong and you're out of position.",
        "feedback_ok": "Calling is too loose — BTN's range dominates your 3-bet calling range.",
        "feedback_poor": "Jamming is reckless with anything less than QQ+.",
    },
    {
        "id": "pf-38",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "You 3-bet from the BTN to 90. BB 4-bets to 220. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 220"},
            {"action": "raise", "label": "Jam for 1000 (all-in)"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You have position and can realize your equity well postflop.",
        "feedback_ok": "4-bet jamming is acceptable with premiums but calling is the default.",
        "feedback_poor": "Folding is too tight — you 3-bet with a wide range from the BTN.",
    },
    {
        "id": "pf-39",
        "position": "CO",
        "stack_depth": 100,
        "action_so_far": "You open from the CO to 25. BTN 3-bets to 90. You 4-bet to 220. BTN 5-bets to 500. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 500"},
            {"action": "raise", "label": "Jam for 1000 (all-in)"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. A 5-bet almost always means AA or KK. Save your chips.",
        "feedback_ok": "Jamming is only correct with AA/KK. Fold everything else.",
        "feedback_poor": "Calling is a huge mistake — you're crushed by the 5-bet range.",
    },
    {
        "id": "pf-40",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "You open from the BTN to 25. SB 3-bets to 90. You 4-bet to 220. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 220"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "raise",
        "feedback_good": "4-betting from the BTN vs SB is standard. You have position and range advantage.",
        "feedback_ok": "Calling is acceptable but 4-bet is higher EV.",
        "feedback_poor": "Folding is too tight — you opened the BTN with a wide range.",
    },
    # --- Short-stack shove/fold (pf-41 to pf-46) ---
    {
        "id": "pf-41",
        "position": "SB",
        "stack_depth": 15,
        "action_so_far": "You are in the SB (15bb effective). Everyone folds to you. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Jam for 150 (all-in)"},
        ],
        "correct_action": "raise",
        "feedback_good": "At 15bb, you should jam or fold from the SB. Jamming is higher EV.",
        "feedback_ok": "Calling is a mistake — you're risking too much of a short stack to just call.",
        "feedback_poor": "Folding is far too tight from the SB at 15bb.",
    },
    {
        "id": "pf-42",
        "position": "BB",
        "stack_depth": 15,
        "action_so_far": "You are in the BB (15bb effective). BTN opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "Jam for 150 (all-in)"},
        ],
        "correct_action": "raise",
        "feedback_good": "At 15bb, a 3-bet jam is the correct play with your strong-but-not-premium range.",
        "feedback_ok": "Calling is acceptable but you're risking too much of your stack.",
        "feedback_poor": "Folding is too tight — you need to defend aggressively at 15bb.",
    },
    {
        "id": "pf-43",
        "position": "UTG",
        "stack_depth": 15,
        "action_so_far": "You are UTG (15bb effective). Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Jam for 150 (all-in)"},
        ],
        "correct_action": "raise",
        "feedback_good": "At 15bb, jam-or-fold is the correct strategy from UTG.",
        "feedback_ok": "Calling is a mistake with a short stack.",
        "feedback_poor": "Folding is too tight from UTG at 15bb.",
    },
    {
        "id": "pf-44",
        "position": "BTN",
        "stack_depth": 15,
        "action_so_far": "You are on the Button (15bb effective). CO opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "Jam for 150 (all-in)"},
        ],
        "correct_action": "raise",
        "feedback_good": "At 15bb, a 3-bet jam is the correct play from the BTN vs CO.",
        "feedback_ok": "Calling is acceptable but jamming is higher EV.",
        "feedback_poor": "Folding is too tight — you need to defend aggressively at 15bb.",
    },
    {
        "id": "pf-45",
        "position": "BB",
        "stack_depth": 10,
        "action_so_far": "You are in the BB (10bb effective). CO opens to 25. BTN calls. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "Jam for 100 (all-in)"},
        ],
        "correct_action": "raise",
        "feedback_good": "At 10bb, you should jam or fold. Jamming with your strong range is correct.",
        "feedback_ok": "Calling is a mistake — you're risking too much of a short stack.",
        "feedback_poor": "Folding is too tight — you need to defend aggressively at 10bb.",
    },
    {
        "id": "pf-46",
        "position": "SB",
        "stack_depth": 10,
        "action_so_far": "You are in the SB (10bb effective). BTN opens to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20"},
            {"action": "raise", "label": "Jam for 100 (all-in)"},
        ],
        "correct_action": "raise",
        "feedback_good": "At 10bb, a 3-bet jam is the correct play from the SB vs BTN.",
        "feedback_ok": "Calling is acceptable but jamming is higher EV.",
        "feedback_poor": "Folding is too tight — you need to defend aggressively at 10bb.",
    },
    # --- Facing limps (pf-47 to pf-50) ---
    {
        "id": "pf-47",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You are in the BB. UTG limps. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "check", "label": "Check"},
            {"action": "raise", "label": "Raise to 40"},
        ],
        "correct_action": "raise",
        "feedback_good": "Raising vs a UTG limp is excellent. You build the pot and isolate the limper.",
        "feedback_ok": "Checking is acceptable but raising is higher EV.",
        "feedback_poor": "Folding is never correct from the BB when you can check for free.",
    },
    {
        "id": "pf-48",
        "position": "SB",
        "stack_depth": 100,
        "action_so_far": "You are in the SB. BTN limps. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "check", "label": "Check"},
            {"action": "raise", "label": "Raise to 40"},
        ],
        "correct_action": "raise",
        "feedback_good": "Raising vs a BTN limp is strong. You build the pot and take initiative.",
        "feedback_ok": "Checking is acceptable but raising is higher EV.",
        "feedback_poor": "Folding is never correct from the SB when you can check for free.",
    },
    {
        "id": "pf-49",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "You are on the Button. MP limps. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "check", "label": "Check"},
            {"action": "raise", "label": "Raise to 40"},
        ],
        "correct_action": "raise",
        "feedback_good": "Raising from the BTN vs a limp is excellent. You have position and initiative.",
        "feedback_ok": "Checking is acceptable but raising is higher EV.",
        "feedback_poor": "Folding is too tight from the BTN.",
    },
    {
        "id": "pf-50",
        "position": "CO",
        "stack_depth": 100,
        "action_so_far": "You are on the Cutoff. Two players limped. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Raise to 40"},
        ],
        "correct_action": "raise",
        "feedback_good": "Raising in a multiway limped pot is strong. You build the pot and take initiative.",
        "feedback_ok": "Calling is acceptable but raising is higher EV.",
        "feedback_poor": "Folding is too tight from the CO.",
    },
    # --- Cold-calling (pf-51 to pf-54) ---
    {
        "id": "pf-51",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You are in the BB. UTG opens to 25. CO calls. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "check", "label": "Check (call 25)"},
            {"action": "raise", "label": "3-bet to 100"},
        ],
        "correct_action": "check",
        "feedback_good": "Good call. You're getting great odds in a multiway pot from the BB.",
        "feedback_ok": "3-bet is acceptable with premiums but calling is the default.",
        "feedback_poor": "Folding is too tight — you need to defend roughly 20-25% vs UTG.",
    },
    {
        "id": "pf-52",
        "position": "BTN",
        "stack_depth": 100,
        "action_so_far": "You are on the Button. UTG opens to 25. MP calls. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You have position and are getting great odds in a multiway pot.",
        "feedback_ok": "3-bet is acceptable with premiums but calling is the default.",
        "feedback_poor": "Folding is too tight — you need to defend roughly 15-20% vs UTG.",
    },
    {
        "id": "pf-53",
        "position": "CO",
        "stack_depth": 100,
        "action_so_far": "You are on the Cutoff. MP opens to 25. BTN calls. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You're getting great odds in a multiway pot.",
        "feedback_ok": "3-bet is acceptable with premiums but calling is the default.",
        "feedback_poor": "Folding is too tight — you need to defend roughly 10-15% vs MP.",
    },
    {
        "id": "pf-54",
        "position": "SB",
        "stack_depth": 100,
        "action_so_far": "You are in the SB. MP opens to 25. CO calls. BTN calls. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You're getting excellent odds in a multiway pot.",
        "feedback_ok": "3-bet is acceptable with premiums but calling is the default.",
        "feedback_poor": "Folding is too tight — you need to defend roughly 10-15% vs MP.",
    },
    # --- Additional spots (pf-55 to pf-57) ---
    {
        "id": "pf-55",
        "position": "UTG",
        "stack_depth": 100,
        "action_so_far": "You are UTG. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 10"},
            {"action": "raise", "label": "Raise to 25"},
        ],
        "correct_action": "raise",
        "feedback_good": "Standard UTG open. You have the best range advantage and should build the pot.",
        "feedback_ok": "Calling is acceptable but raising is higher EV.",
        "feedback_poor": "Folding is too tight from UTG.",
    },
    {
        "id": "pf-56",
        "position": "MP",
        "stack_depth": 100,
        "action_so_far": "You are MP. UTG raises to 25. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 25"},
            {"action": "raise", "label": "3-bet to 90"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. UTG's open range is very strong and you're out of position.",
        "feedback_ok": "Calling is too loose — UTG's range dominates your MP calling range.",
        "feedback_poor": "3-betting here is reckless. UTG's range is too strong.",
    },
    {
        "id": "pf-57",
        "position": "BB",
        "stack_depth": 100,
        "action_so_far": "You are in the BB. CO opens to 25. BTN calls. Blinds 5/10.",
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "check", "label": "Check (call 25)"},
            {"action": "raise", "label": "3-bet to 100"},
        ],
        "correct_action": "check",
        "feedback_good": "Good call. You're getting great odds in a multiway pot from the BB.",
        "feedback_ok": "3-bet is acceptable with premiums but calling is the default.",
        "feedback_poor": "Folding is too tight — you need to defend roughly 15-20% vs CO.",
    },
]


def get_preflop_drills(count: int = 10) -> list[dict[str, Any]]:
    """Return `count` random preflop drill scenarios."""
    if count >= len(SCENARIOS):
        return random.sample(SCENARIOS, len(SCENARIOS))
    return random.sample(SCENARIOS, count)
