"""Postflop drill scenarios for the Drill Lab module."""

import random
from typing import Any

SCENARIOS: list[dict[str, Any]] = [
    # --- C-bet or check ---
    {
        "id": "po-01",
        "situation": "You are on the Button. Flop is K♠ 9♦ 4♣. You have A♠K♦. BB checks.",
        "board": ["K♠", "9♦", "4♣"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Bet 15"},
            {"action": "bet", "label": "Bet 40"},
        ],
        "correct_action": "bet",
        "feedback_good": "C-betting top pair top kicker on a dry board is standard. You build the pot and deny equity.",
        "feedback_ok": "Checking is acceptable but betting is higher EV — you have the best hand most of the time.",
        "feedback_poor": "Don't overthink this — top pair top kicker is a clear c-bet.",
    },
    {
        "id": "po-02",
        "situation": "You are in the BB. Flop is Q♠ J♠ 4♣. You have 7♥7♦. BB checks to you.",
        "board": ["Q♠", "J♠", "4♣"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Bet 15"},
            {"action": "bet", "label": "Bet 40"},
        ],
        "correct_action": "check",
        "feedback_good": "Checking is correct. You have middle pair on a wet board — betting would be a mistake.",
        "feedback_ok": "A small bet is acceptable but checking is the higher-EV line.",
        "feedback_poor": "A large bet is a clear mistake — you're behind most of the checking range.",
    },
    {
        "id": "po-03",
        "situation": "You are on the CO. Flop is A♠ 9♦ 4♣. You have A♦K♣. BTN checks.",
        "board": ["A♠", "9♦", "4♣"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Bet 15"},
            {"action": "bet", "label": "Bet 40"},
        ],
        "correct_action": "bet",
        "feedback_good": "C-betting top pair on an Ace-high dry board is standard. You build the pot.",
        "feedback_ok": "Checking is acceptable but betting is higher EV.",
        "feedback_poor": "Don't slow-play top pair on this board.",
    },
    # --- Barrel or give up ---
    {
        "id": "po-04",
        "situation": "You c-bet the flop (K♠ 9♦ 4♣) and get called. Turn is 2♥. You have A♠K♦.",
        "board": ["K♠", "9♦", "4♣", "2♥"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Bet 30"},
            {"action": "bet", "label": "Bet 80"},
        ],
        "correct_action": "bet",
        "feedback_good": "Barreling is correct. The 2♥ is a blank and you still have top pair top kicker.",
        "feedback_ok": "Checking is acceptable but betting is higher EV.",
        "feedback_poor": "Don't give up on this board — you have the best hand most of the time.",
    },
    {
        "id": "po-05",
        "situation": "You c-bet the flop (K♠ 9♦ 4♣) and get called. Turn is Q♥. You have 7♦7♠.",
        "board": ["K♠", "9♦", "4♣", "Q♥"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Bet 30"},
            {"action": "bet", "label": "Bet 80"},
        ],
        "correct_action": "check",
        "feedback_good": "Checking is correct. The Q♥ brings many better hands. Your 77 is likely behind.",
        "feedback_ok": "A small bluff is acceptable but checking is the higher-EV line.",
        "feedback_poor": "A large barrel is a clear mistake — you're behind most of the calling range.",
    },
    {
        "id": "po-06",
        "situation": "You c-bet the flop (J♠ 8♦ 3♣) and get called. Turn is J♦. You have A♣K♣.",
        "board": ["J♠", "8♦", "3♣", "J♦"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Bet 30"},
            {"action": "bet", "label": "Bet 80"},
        ],
        "correct_action": "check",
        "feedback_good": "Checking is correct. The paired Jack kills your overcards — many better hands now beat you.",
        "feedback_ok": "A small bluff is acceptable but checking is the higher-EV line.",
        "feedback_poor": "A large barrel is a clear mistake — you're behind most of the calling range.",
    },
    # --- Value vs bluff ---
    {
        "id": "po-07",
        "situation": "You are on the BTN. River is K♠ 9♦ 4♣ 2♥ 8♠. You have A♠K♦. BB bets 40.",
        "board": ["K♠", "9♦", "4♣", "2♥", "8♠"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 40"},
            {"action": "raise", "label": "Raise to 120"},
        ],
        "correct_action": "raise",
        "feedback_good": "Raising for value is correct. You have top pair top kicker and should extract maximum value.",
        "feedback_ok": "Calling is acceptable but raising is higher EV.",
        "feedback_poor": "Folding is a clear mistake — you have a very strong hand.",
    },
    {
        "id": "po-08",
        "situation": "You are on the BB. River is Q♠ J♠ 4♣ 2♥ 8♠. You have 7♦7♠. BTN bets 40.",
        "board": ["Q♠", "J♠", "4♣", "2♥", "8♠"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 40"},
            {"action": "raise", "label": "Raise to 120"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. The BTN's range is very strong on this board and 77 is likely beaten.",
        "feedback_ok": "Calling is too loose — the BTN's range dominates your hand.",
        "feedback_poor": "Raising is reckless — you're behind most of the betting range.",
    },
    {
        "id": "po-09",
        "situation": "You are on the CO. River is A♠ K♦ 9♣ 7♥ 2♠. You have A♦Q♣. BB bets 40.",
        "board": ["A♠", "K♦", "9♣", "7♥", "2♠"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 40"},
            {"action": "raise", "label": "Raise to 120"},
        ],
        "correct_action": "call",
        "feedback_good": "Calling is correct. You have top pair but should not raise — you're behind AK, A9, KQ.",
        "feedback_ok": "Folding is too tight — you have top pair and should call.",
        "feedback_poor": "Raising is a mistake — you're behind most of the betting range.",
    },
    # --- Fold to 3-bet ---
    {
        "id": "po-10",
        "situation": "You open from MP to 25. BB 3-bets to 90. You have K♠J♠. Blinds 5/10.",
        "board": [],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 90"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. KJs is too weak to call a 3-bet from the BB out of position.",
        "feedback_ok": "Calling is too loose — you're out of position and dominated by the BB's range.",
        "feedback_poor": "4-betting is reckless — KJs is not strong enough.",
    },
    {
        "id": "po-11",
        "situation": "You open from CO to 25. BB 3-bets to 90. You have A♠Q♦. Blinds 5/10.",
        "board": [],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 90"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. AQo is strong enough to call a 3-bet but not strong enough to 4-bet.",
        "feedback_ok": "4-bet is acceptable with premiums but calling is the default.",
        "feedback_poor": "Folding is too tight — AQo is too strong to fold to a single 3-bet.",
    },
    {
        "id": "po-12",
        "situation": "You open from BTN to 25. BB 3-bets to 90. You have A♠5♠. Blinds 5/10.",
        "board": [],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 90"},
            {"action": "raise", "label": "4-bet to 220"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. A5s has great playability and blocker value. Perfect for calling a 3-bet.",
        "feedback_ok": "4-bet is acceptable but calling is the default.",
        "feedback_poor": "Folding is too tight — A5s is too strong to fold.",
    },
    # --- Draw decisions ---
    {
        "id": "po-13",
        "situation": "You are on the BTN. Flop is K♠ 9♦ 4♣. You have 8♠7♠ (open-ended straight draw). BB bets 20.",
        "board": ["K♠", "9♦", "4♣"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20"},
            {"action": "raise", "label": "Raise to 60"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You have an open-ended straight draw with two overcards — plenty of equity.",
        "feedback_ok": "Raising is acceptable but calling is the default.",
        "feedback_poor": "Folding is too tight — you have too much equity to fold.",
    },
    {
        "id": "po-14",
        "situation": "You are on the BB. Flop is Q♠ J♠ 4♣. You have 9♠8♠ (flush draw + gutshot). BTN bets 20.",
        "board": ["Q♠", "J♠", "4♣"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20"},
            {"action": "raise", "label": "Raise to 60"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You have a flush draw and a gutshot — plenty of equity to continue.",
        "feedback_ok": "Raising is acceptable but calling is the default.",
        "feedback_poor": "Folding is too tight — you have too much equity to fold.",
    },
    {
        "id": "po-15",
        "situation": "You are on the CO. Flop is A♠ 9♦ 4♣. You have 5♦5♣. BB bets 20.",
        "board": ["A♠", "9♦", "4♣"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20"},
            {"action": "raise", "label": "Raise to 60"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. The Ace on board kills your 55 — many better hands beat you.",
        "feedback_ok": "Calling is too loose — the Ace on board is a major concern.",
        "feedback_poor": "Raising is reckless — you're behind most of the betting range.",
    },
    {
        "id": "po-16",
        "situation": "You are on the BTN. Flop is K♠ 9♦ 4♣. You have A♠5♠ (nut flush draw). BB bets 20.",
        "board": ["K♠", "9♦", "4♣"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20"},
            {"action": "raise", "label": "Raise to 60"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. The nut flush draw has massive equity — you should continue.",
        "feedback_ok": "Raising is acceptable but calling is the default.",
        "feedback_poor": "Folding is too tight — the nut flush draw has too much equity.",
    },
    {
        "id": "po-17",
        "situation": "You are on the BB. Turn is K♠ 9♦ 4♣ 2♥. You have A♠K♦. BTN bets 40.",
        "board": ["K♠", "9♦", "4♣", "2♥"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 40"},
            {"action": "raise", "label": "Raise to 120"},
        ],
        "correct_action": "raise",
        "feedback_good": "Raising for value is correct. You have top pair top kicker on a dry board.",
        "feedback_ok": "Calling is acceptable but raising is higher EV.",
        "feedback_poor": "Folding is a clear mistake — you have a very strong hand.",
    },
    {
        "id": "po-18",
        "situation": "You are on the SB. River is Q♠ J♠ 4♣ 2♥ 8♠. You have A♠K♣. BTN bets 40.",
        "board": ["Q♠", "J♠", "4♣", "2♥", "8♠"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 40"},
            {"action": "raise", "label": "Raise to 120"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You have top pair top kicker but should not raise — you're behind sets and two pair.",
        "feedback_ok": "Folding is too tight — you have top pair and should call.",
        "feedback_poor": "Raising is a mistake — you're behind most of the betting range.",
    },
    # --- Check-raise spots (po-19 to po-21) ---
    {
        "id": "po-19",
        "situation": "You are in the BB. Flop is 8♠ 7♠ 4♦. You have 9♠6♠ (open-ended straight draw + flush draw). BTN bets 20.",
        "board": ["8♠", "7♠", "4♦"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20"},
            {"action": "raise", "label": "Check-raise to 60"},
        ],
        "correct_action": "raise",
        "feedback_good": "Check-raising is excellent. You have a monster draw with massive equity — build the pot.",
        "feedback_ok": "Calling is acceptable but check-raising is higher EV with this much equity.",
        "feedback_poor": "Folding is a clear mistake — you have too much equity to fold.",
    },
    {
        "id": "po-20",
        "situation": "You are on the BTN. Flop is K♦ 9♣ 3♠. You have A♠K♠ (top pair top kicker). BB bets 20.",
        "board": ["K♦", "9♣", "3♠"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20"},
            {"action": "raise", "label": "Raise to 60"},
        ],
        "correct_action": "raise",
        "feedback_good": "Raising for value is correct. You have top pair top kicker and should build the pot.",
        "feedback_ok": "Calling is acceptable but raising is higher EV.",
        "feedback_poor": "Folding is a clear mistake — you have a very strong hand.",
    },
    {
        "id": "po-21",
        "situation": "You are in the BB. Flop is J♠ 8♦ 3♣. You have J♦7♠ (top pair weak kicker). BTN bets 20.",
        "board": ["J♠", "8♦", "3♣"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20"},
            {"action": "raise", "label": "Check-raise to 60"},
        ],
        "correct_action": "call",
        "feedback_good": "Good call. You have top pair but weak kicker — calling is the default.",
        "feedback_ok": "Check-raising is acceptable but calling is the higher-EV line.",
        "feedback_poor": "Folding is too tight — you have top pair.",
    },
    # --- Donk betting (po-22 to po-24) ---
    {
        "id": "po-22",
        "situation": "You are in the BB. Flop is A♠ 7♦ 3♣. You have A♣K♦. You are first to act.",
        "board": ["A♠", "7♦", "3♣"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Donk bet 15"},
            {"action": "bet", "label": "Donk bet 40"},
        ],
        "correct_action": "check",
        "feedback_good": "Checking is correct. Donk betting top pair into the preflop raiser is generally a mistake.",
        "feedback_ok": "A small donk bet is acceptable but checking is the higher-EV line.",
        "feedback_poor": "A large donk bet is a clear mistake — you should check to the raiser.",
    },
    {
        "id": "po-23",
        "situation": "You are on the BTN. Flop is 9♠ 6♦ 2♣. You have 8♠7♠ (open-ended straight draw). BB checks.",
        "board": ["9♠", "6♦", "2♣"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Bet 15"},
            {"action": "bet", "label": "Bet 40"},
        ],
        "correct_action": "bet",
        "feedback_good": "Betting is correct. You have a strong draw and should build the pot.",
        "feedback_ok": "Checking is acceptable but betting is higher EV.",
        "feedback_poor": "Don't miss the chance to build the pot with your strong draw.",
    },
    {
        "id": "po-24",
        "situation": "You are in the BB. Flop is K♠ Q♦ 7♣. You have Q♠J♠ (second pair). BTN checks.",
        "board": ["K♠", "Q♦", "7♣"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Bet 15"},
            {"action": "bet", "label": "Bet 40"},
        ],
        "correct_action": "check",
        "feedback_good": "Checking is correct. Second pair is not strong enough to bet for value.",
        "feedback_ok": "A small bet is acceptable but checking is the higher-EV line.",
        "feedback_poor": "A large bet is a clear mistake — you're behind most of the checking range.",
    },
    # --- Overbet spots (po-25 to po-27) ---
    {
        "id": "po-25",
        "situation": "You are on the BTN. River is A♠ K♦ 9♣ 7♥ 2♠. You have A♠K♣ (top two pair). BB checks. Pot is 100.",
        "board": ["A♠", "K♦", "9♣", "7♥", "2♠"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Bet 60 (60% pot)"},
            {"action": "bet", "label": "Overbet 150 (150% pot)"},
        ],
        "correct_action": "bet",
        "feedback_good": "A standard bet is correct. You have top two pair and should extract value.",
        "feedback_ok": "Overbetting is acceptable with premiums but a standard bet is the default.",
        "feedback_poor": "Checking is a mistake — you have a very strong hand and should bet for value.",
    },
    {
        "id": "po-26",
        "situation": "You are on the BB. Flop is A♠ A♦ 7♣. You have A♥K♠ (top set). BTN bets 20. Pot is 50.",
        "board": ["A♠", "A♦", "7♣"],
        "options": [
            {"action": "call", "label": "Call 20"},
            {"action": "raise", "label": "Raise to 60"},
            {"action": "raise", "label": "Overbet to 120"},
        ],
        "correct_action": "raise",
        "feedback_good": "Raising is correct. You have top set and should build the pot.",
        "feedback_ok": "Overbetting is acceptable but a standard raise is the default.",
        "feedback_poor": "Just calling is too passive — you have the nuts on this board.",
    },
    {
        "id": "po-27",
        "situation": "You are on the BTN. River is K♠ 9♦ 4♣ 2♥ 8♠. You have 7♦7♠ (bluff spot). BB checks. Pot is 100.",
        "board": ["K♠", "9♦", "4♣", "2♥", "8♠"],
        "options": [
            {"action": "check", "label": "Check"},
            {"action": "bet", "label": "Bet 60 (60% pot)"},
            {"action": "bet", "label": "Overbet 150 (150% pot)"},
        ],
        "correct_action": "bet",
        "feedback_good": "A standard bluff bet is correct. The board texture favors your range.",
        "feedback_ok": "Overbetting is acceptable but a standard bet is the default.",
        "feedback_poor": "Checking is a missed opportunity — you should bluff this river.",
    },
    # --- Float plays (po-28 to po-30) ---
    {
        "id": "po-28",
        "situation": "You are on the BTN. Flop is K♠ 9♦ 4♣. You have Q♠J♠ (no pair). BB bets 20.",
        "board": ["K♠", "9♦", "4♣"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20 (float)"},
            {"action": "raise", "label": "Raise to 60"},
        ],
        "correct_action": "call",
        "feedback_good": "Good float. You have position and backdoor draws — you can take the pot away on later streets.",
        "feedback_ok": "Folding is acceptable but floating is higher EV with your positional advantage.",
        "feedback_poor": "Raising is reckless — you have no pair and no draw.",
    },
    {
        "id": "po-29",
        "situation": "You are on the CO. Flop is J♠ 8♦ 3♣. You have A♠K♦ (overcards). BTN bets 20.",
        "board": ["J♠", "8♦", "3♣"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20 (float)"},
            {"action": "raise", "label": "Raise to 60"},
        ],
        "correct_action": "call",
        "feedback_good": "Good float. You have two overcards and position — you can take the pot away on later streets.",
        "feedback_ok": "Folding is acceptable but floating is higher EV with your overcards.",
        "feedback_poor": "Raising is reckless — you have no pair yet.",
    },
    {
        "id": "po-30",
        "situation": "You are on the BB. Flop is Q♠ 7♦ 2♣. You have 5♠4♠ (backdoor flush draw). BTN bets 20.",
        "board": ["Q♠", "7♦", "2♣"],
        "options": [
            {"action": "fold", "label": "Fold"},
            {"action": "call", "label": "Call 20"},
            {"action": "raise", "label": "Raise to 60"},
        ],
        "correct_action": "fold",
        "feedback_good": "Correct fold. You have very little equity and are out of position.",
        "feedback_ok": "Calling is too loose — you have almost no equity and no position.",
        "feedback_poor": "Raising is reckless — you have nothing.",
    },
]


def get_postflop_drills(count: int = 10) -> list[dict[str, Any]]:
    """Return `count` random postflop drill scenarios."""
    if count >= len(SCENARIOS):
        return random.sample(SCENARIOS, len(SCENARIOS))
    return random.sample(SCENARIOS, count)
